const names = [
    'Aaran',
    'Aaren',
    'Aarez',
    'Aarman',
    'Aaron',
    'Aaron-James',
    'Aarron',
    'Aaryan',
    'Aaryn',
    'Aayan',
    'Aazaan',
    'Abaan',
    'Abbas',
    'Abdallah',
    'Abdalroof',
    'Abdihakim',
    'Abdirahman',
    'Abdisalam',
    'Abdul',
    'Abdul-Aziz',
    'Abdulbasir',
    'Abdulkadir',
    'Abdulkarem',
    'Smith',
    'Jones',
    'Coollastname',
    'enter_name_here',
    'Ze',
    'Zechariah',
    'Zeek',
    'Zeeshan',
    'Zeid',
    'Zein',
    'Zen',
    'Zendel',
    'Zenith',
    'Zennon',
    'Zeph',
    'Zerah',
    'Zhen',
    'Zhi',
    'Zhong',
    'Zhuo',
    'Zi',
    'Zidane',
    'Zijie',
    'Zinedine',
    'Zion',
    'Zishan',
    'Ziya',
    'Ziyaan',
    'Zohaib',
    'Zohair',
    'Zoubaeir',
    'Zubair',
    'Zubayr',
    'Zuriel',
    'Xander',
    'Jared',
    'Courtney',
    'Gillian',
    'Clark',
    'Jared',
    'Grace',
    'Kelsey',
    'Tamar',
    'Alex',
    'Mark',
    'Tamar',
    'Farish',
    'Sarah',
    'Nathaniel',
    'Parker',
  ];

  const thought = [
    'How much wood did a woodchuck chuck?',
    'Who created the 9-5 work week?',
    'Why is there so much weight on going to college',
    'How do you live a happy life?',
    'What is the happiest known animal?',
    'What is the smartest animal?',
    'I think React is going to be a very helpful tool',
    'What is the average life of a plant?',
    'How is success defined?',
    "I'm thinking of how to work smarter not harder",
    'How long does it take to make a baby blanket?',
    'What is the happiest conuntry to visit?',
    'What is the happiest state in the United States to visit?',
    'Who created last names?',
  ];

  //selecting a random element from array-- return random item from that array.
  const getRandomArrItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

  //returns random full name
  const getRandomName = () =>
  `${getRandomArrItem(names)} ${getRandomArrItem(names)}`;

  //returns random thought
  const getRandomThought = () =>
  `${getRandomArrItem(thought)}`;

  //Export the functions for use in seed.js
  module.exports = { getRandomName, getRandomThought};